### ISSUE TITLE
Selecting a File in the OneDrive Block in the Editor Fails

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/onedrive#5]
When navigating to the OneDrive file chooser from the Select a file option, once a file is selected it doesn't embed back into the post: 

![2024-12-04_11-40-50 (1)](https://github.com/user-attachments/assets/556fe00f-56d3-4dc2-8ad1-8b725faf6f60)

**Comment by r-a-y** [comment]
I believe I have a fix for this. Can you purge your browser cache or do a hard refresh and try embedding a OneDrive item?

**Comment by mrjarbenne** [comment]
Are you seeing this on the front of subdomains? 

<img width="1613" alt="2024-12-05_10-50-35" src="https://github.com/user-attachments/assets/30cc09b9-aa5c-43fe-a8f0-27485bb35398">

**Comment by mrjarbenne** [comment]
Seeing it here on dev.commons.hwdsb.on.ca and sandbox.commons.hwdsb.on.ca

Seems to be only occurring when you are logged in. and it's not all the subdomains, for example 416.commons.hwdsb.on.ca seems fine.

**Comment by r-a-y** [comment]
Sorry! I had some debug code that I forgot to uncomment. Let me know if you are still experiencing this.

**Comment by mrjarbenne** [comment]
All good now.

**Comment by mrjarbenne** [comment]
And the embedded video from OneDrive is now working as well.
